name: ada_tugas
description: An app for students
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  env_flutter: ^0.1.4
  envify: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  flutter_secure_storage: ^5.0.2
  go_router: ^4.1.0
  intl: ^0.17.0
  supabase: ^0.3.4+1

dev_dependencies:
  build_runner: ^2.1.11
  envify_generator: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
